# Generated by Django 4.1.3 on 2023-02-15 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MainsGas", models.IntegerField()),
                ("Fuel", models.IntegerField()),
                ("Oil", models.IntegerField()),
                ("Coal", models.IntegerField()),
                ("Wood", models.IntegerField()),
                ("GridElectricity", models.IntegerField()),
                ("Electricity", models.IntegerField()),
                ("WFLandfill", models.IntegerField()),
                ("WFReuse", models.IntegerField()),
                ("WFCharity", models.IntegerField()),
                ("BottleRecycling", models.IntegerField()),
                ("AluminiumRecycling", models.IntegerField()),
                ("GWLandfill", models.IntegerField()),
                ("GWRecycling", models.IntegerField()),
                ("SpecialWaste", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CalculatorConstants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MainsGas", models.FloatField()),
                ("Fuel", models.FloatField()),
                ("Oil", models.FloatField()),
                ("Coal", models.FloatField()),
                ("Wood", models.FloatField()),
                ("GridElectricity", models.FloatField()),
                ("Electricity", models.FloatField()),
                ("WFLandfill", models.FloatField()),
                ("WFReuse", models.FloatField()),
                ("WFCharity", models.FloatField()),
                ("BottleRecycling", models.FloatField()),
                ("AluminiumRecycling", models.FloatField()),
                ("GWLandfill", models.FloatField()),
                ("GWRecycling", models.FloatField()),
                ("SpecialWaste", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="BrewdogUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("company", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("phone", models.CharField(max_length=50, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brewdogUser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
