# Generated by Django 4.1.3 on 2022-11-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brewdog_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MainsGas", models.IntegerField()),
                ("Fuel", models.IntegerField()),
                ("Oil", models.IntegerField()),
                ("Coal", models.IntegerField()),
                ("Wood", models.IntegerField()),
                ("GridElectricity", models.IntegerField()),
                ("Electricity", models.IntegerField()),
                ("WFLandfill", models.IntegerField()),
                ("WFReuse", models.IntegerField()),
                ("WFCharity", models.IntegerField()),
                ("BottleRecycling", models.IntegerField()),
                ("AluminiumRecycling", models.IntegerField()),
                ("GWLandfill", models.IntegerField()),
                ("GWRecycling", models.IntegerField()),
                ("SpecialWaste", models.IntegerField()),
            ],
        ),
    ]
