# Generated by Django 4.1.3 on 2023-03-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewdog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorconstants',
            name='Coal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calculatorconstants',
            name='Fuel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calculatorconstants',
            name='MainsGas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calculatorconstants',
            name='Oil',
            field=models.FloatField(),
        ),
    ]
