# Generated by Django 4.1.3 on 2023-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewdog_api', '0004_user_last_login_alter_user_company_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainsGas', models.FloatField()),
                ('Fuel', models.FloatField()),
                ('Oil', models.FloatField()),
                ('Coal', models.FloatField()),
                ('Wood', models.FloatField()),
                ('GridElectricity', models.FloatField()),
                ('Electricity', models.FloatField()),
                ('WFLandfill', models.FloatField()),
                ('WFReuse', models.FloatField()),
                ('WFCharity', models.FloatField()),
                ('BottleRecycling', models.FloatField()),
                ('AluminiumRecycling', models.FloatField()),
                ('GWLandfill', models.FloatField()),
                ('GWRecycling', models.FloatField()),
                ('SpecialWaste', models.FloatField()),
            ],
        ),
    ]
