# Generated by Django 2.2.26 on 2022-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brewdogCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breweryName', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=200)),
            ],
        ),
    ]
